version: '3.8'  # Versão do Docker Compose

services:
  postgres:  # Nome do serviço
    image: postgres:14  # Imagem oficial do PostgreSQL (versão 14)
    container_name: ${POSTGRES_DATABASE}  # Nome do contêiner
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Usuário do banco de dados
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Senha do banco de dados
      POSTGRES_DB: ${POSTGRES_DATABASE}  # Nome do banco de dados
    ports:
      - "5432:6060"  # Mapeia a porta 5432 do contêiner para a porta 5432 do host
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume para persistir os dados
    restart: always  # Reinicia o contêiner automaticamente em caso de falha

volumes:
  postgres_data:  # Define um volume para persistir os dados do PostgreSQL